name = "CombinedUncertainDiffEq"
uuid = "2afec61b-a96c-4160-b44a-dd4438f544f4"
authors = ["Jonnie Diegelman <jonniediegelman@gmail.com> and contributors"]
version = "0.1.1"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DiffEqUncertainty = "ef61062a-5684-51dc-bb67-a0fcdec5c97d"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
ComponentArrays = "0.11"
DiffEqUncertainty = "1.8"
DifferentialEquations = "6.18"
Distributions = "0.24"
IntervalArithmetic = "0.19"
Setfield = "0.8"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
