name = "CombinedUncertainDiffEq"
uuid = "2afec61b-a96c-4160-b44a-dd4438f544f4"
authors = ["Jonnie Diegelman <jonniediegelman@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DiffEqUncertainty = "ef61062a-5684-51dc-bb67-a0fcdec5c97d"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
ReachabilityAnalysis = "1e97bd63-91d1-579d-8e8d-501d2b57c93f"

[compat]
DiffEqUncertainty = "1"
IntervalArithmetic = "0.19"
ReachabilityAnalysis = "0.15"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
